ServerName localhost

<VirtualHost *:80>
    DocumentRoot /var/www/indiba/public

    <Directory /var/www/indiba/public>
        Options -Indexes -MultiViews +FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    <Directory /var/www/indiba/public/uploads>
        AllowOverride None
        Options -Indexes -ExecCGI
        <FilesMatch "(?i)\.(php|phtml|phar|html|htm|js|svg)$">
            Require all denied
        </FilesMatch>
    </Directory>

    ErrorLog /proc/self/fd/2
    CustomLog /proc/self/fd/1 combined
</VirtualHost>
