memory_limit = 512M
date.timezone = Asia/Kuala_Lumpur
display_errors = Off
log_errors = On
expose_php = Off
upload_max_filesize = 20M
post_max_size = 24M
session.use_strict_mode = 1
session.cookie_httponly = 1
session.cookie_samesite = Lax
max_input_vars = 10000
mysqlnd.net_read_timeout = 5
