<?php
declare(strict_types=1);
try {
    $page = cmsPage((int)($_GET['id'] ?? 0)); $html = cmsHtml($page); $document = cmsDocument($html);
    $mode = in_array($_GET['mode'] ?? '', ['classic','visual','content','html'], true) ? $_GET['mode'] : 'classic';
    $classic = $mode === 'classic' ? cmsClassicPrepare($document) : null;
    [$texts, $images] = cmsEditable($document); $rich = cmsRichBlocks($document);
    $groups = $db->query('SELECT DISTINCT group_name FROM indiba_cms_pages ORDER BY group_name')->fetchAll(PDO::FETCH_COLUMN);
    $meta = (new DOMXPath($document))->query('//meta[translate(@name,"ABCDEFGHIJKLMNOPQRSTUVWXYZ","abcdefghijklmnopqrstuvwxyz")="description"]')->item(0);
    $description = $page['meta_description'] ?? ($meta instanceof DOMElement ? $meta->getAttribute('content') : '');
    $revisionQuery = $db->prepare('SELECT COUNT(*) FROM indiba_cms_revisions WHERE page_id = ?'); $revisionQuery->execute([$page['id']]); $revisionCount = (int)$revisionQuery->fetchColumn();
?>
<div class="editor-top"><a href="/admin/?view=pages">← All pages</a><div class="editor-links"><a href="/admin/?view=preview&id=<?= $page['id'] ?>" target="_blank" rel="noopener">Preview saved page ↗</a><?php if ($page['status']==='published'): ?><a href="<?= cmsEscape($page['route']) ?>" target="_blank" rel="noopener">View live ↗</a><?php endif ?></div></div>
<?php if ($page['status']==='trashed'): ?><section class="panel"><h2>This page is in Trash</h2><p class="muted">Restore it as a draft to continue editing.</p><form method="post"><?= csrfInput() ?><input type="hidden" name="action" value="page_status"><input type="hidden" name="id" value="<?= $page['id'] ?>"><input type="hidden" name="version" value="<?= $page['version'] ?>"><input type="hidden" name="target_status" value="draft"><button>Restore as draft</button></form></section>
<?php else: ?>
<form method="post" id="page-editor"><?= csrfInput() ?><input type="hidden" name="action" value="save_page"><input type="hidden" name="id" value="<?= $page['id'] ?>"><input type="hidden" name="version" value="<?= $page['version'] ?>"><input type="hidden" name="mode" value="<?= $mode ?>">
<label class="page-title-field"><span>Page title</span><input name="title" value="<?= cmsEscape($page['title']) ?>" required maxlength="490"></label>
<div class="cms-editor-layout <?= $mode==='classic' ? 'classic-mode' : '' ?>"><div class="cms-editor-main"><nav class="tabs" aria-label="Editor mode"><?php foreach (['classic'=>'Classic editor','visual'=>'Simple editor','content'=>'All text & images','html'=>'HTML source'] as $key=>$label): ?><a class="<?= $mode===$key ? 'selected' : '' ?>" href="?view=edit&id=<?= $page['id'] ?>&mode=<?= $key ?>"><?= $label ?></a><?php endforeach ?></nav>
<?php if ($mode==='classic'): ?><section class="panel classic-panel"><div class="classic-heading"><div><h2>Page content</h2><p class="muted">Write, format, and arrange content with the classic editor.</p></div><button type="button" class="secondary" id="classic-add-media">Add media</button></div><?php if ($classic['available']): ?><div class="classic-view-switch" role="group" aria-label="Classic editor view"><button type="button" id="classic-visual-button" aria-pressed="true" aria-controls="classic-content" disabled>Visual</button><button type="button" id="classic-code-button" aria-pressed="false" aria-controls="classic-code" disabled>Code</button></div><input type="hidden" name="classic_changed" id="classic-changed" value="0"><textarea id="classic-config" hidden><?= cmsEscape(json_encode(['css'=>$classic['css'],'styles'=>$classic['styles'],'body_class'=>$classic['body_class']],JSON_UNESCAPED_SLASHES | JSON_INVALID_UTF8_SUBSTITUTE)) ?></textarea><textarea name="classic_content" id="classic-content" aria-label="Page content" rows="25"><?= cmsEscape($classic['content']) ?></textarea><textarea id="classic-code" class="classic-code-editor" aria-label="Page content HTML" aria-describedby="classic-code-help" spellcheck="false" autocapitalize="off" autocomplete="off" rows="25" hidden></textarea><p class="classic-help" id="classic-code-help">Switch between Visual and Code to edit the same page content. Code uses HTML; original protected widgets are restored when saving. Use HTML source to edit the full page document.</p><div id="classic-status" class="field-help" role="status"></div><?php else: ?><p class="muted">This page has a custom layout. Open the Simple editor or HTML source to edit it.</p><?php endif ?></section>
<?php elseif ($mode==='html'): ?><section class="panel"><h2>Page HTML</h2><p class="muted">Edit layout, links, and background images here.</p><textarea name="html" class="source-editor" spellcheck="false" aria-label="Page HTML source"><?= cmsEscape($html) ?></textarea></section>
<?php else: ?><section class="panel"><div class="panel-heading"><div><h2><?= $mode==='visual' ? 'Page content' : 'All page text' ?></h2><p class="muted"><?= $mode==='visual' ? 'Edit headings and paragraphs with formatting. The page keeps its existing layout.' : 'Includes navigation, footer, buttons, and labels. Changes affect this page.' ?></p></div><input id="content-search" placeholder="Find text on this page" aria-label="Find editable text"></div>
<?php if ($mode==='visual'): ?><div class="format-toolbar" role="toolbar" aria-label="Text formatting"><button type="button" data-format="strong" aria-label="Bold"><strong>B</strong></button><button type="button" data-format="em" aria-label="Italic"><em>I</em></button><button type="button" data-format="u" aria-label="Underline"><u>U</u></button><button type="button" data-format="link">Add link</button><button type="button" data-format="clear">Clear formatting</button><span>Select text, then format it.</span></div><div class="rich-blocks"><?php foreach ($rich as $key=>$node): ?><div class="rich-block"><span class="block-label"><?= cmsEscape(strtoupper($node->tagName)) ?></span><div class="rich-editor rich-<?= cmsEscape($node->tagName) ?>" contenteditable="true" role="textbox" aria-multiline="true" aria-label="Edit <?= cmsEscape($node->tagName) ?> content" data-field="rich-<?= $key ?>"><?= cmsSafeRichText(cmsInnerHtml($node)) ?></div><textarea hidden id="rich-<?= $key ?>" name="rich[<?= $key ?>]" data-original="<?= cmsEscape(cmsSafeRichText(cmsInnerHtml($node))) ?>"><?= cmsEscape(cmsInnerHtml($node)) ?></textarea></div><?php endforeach ?></div><?php if (!$rich): ?><p class="muted">Use All text & images to edit this page's custom content.</p><?php endif ?>
<?php if ($page['source_file']===''): ?><div id="new-content-blocks"></div><div class="add-blocks"><span>Add content</span><button type="button" class="secondary add-content-block" data-type="p">+ Paragraph</button><button type="button" class="secondary add-content-block" data-type="h2">+ Heading</button><button type="button" class="secondary add-content-block" data-type="blockquote">+ Quote</button></div><?php endif ?>
<?php else: ?><div class="content-fields"><?php foreach ($texts as $key=>$node): ?><label class="text-block"><span><?= cmsEscape(strtoupper($node->parentNode->nodeName)) ?></span><textarea name="text[<?= $key ?>]" rows="<?= strlen(trim($node->nodeValue))>180 ? 3 : 1 ?>"><?= cmsEscape(trim($node->nodeValue)) ?></textarea></label><?php endforeach ?></div><?php endif ?></section>
<section class="panel"><h2>Page images</h2><p class="muted">Choose an image from the media library or paste a file URL. Background images can be changed in HTML source.</p><div class="image-fields"><?php foreach ($images as $key=>$node): ?><div class="image-edit"><img src="<?= cmsEscape($node->getAttribute('src')) ?>" alt="" loading="lazy"><div><label>Image URL<input id="image-<?= $key ?>" name="images[<?= $key ?>][src]" value="<?= cmsEscape($node->getAttribute('src')) ?>"></label><button type="button" class="secondary choose-image" data-target="image-<?= $key ?>">Choose image</button><label>Alternative text<input name="images[<?= $key ?>][alt]" value="<?= cmsEscape($node->getAttribute('alt')) ?>"></label></div></div><?php endforeach ?></div></section><?php endif ?>
</div><aside class="cms-editor-settings"><section class="panel"><h2>Publication</h2><span class="badge <?= $page['status'] ?>"><?= cmsEscape($page['status']) ?></span><label>Status<select name="status"><option value="draft" <?= $page['status']==='draft' ? 'selected' : '' ?>>Draft</option><option value="published" <?= $page['status']==='published' ? 'selected' : '' ?>>Published</option></select></label><p class="muted">Updated <?= cmsEscape($page['updated_at']) ?></p><button class="full-width">Save changes</button><a class="setting-link" href="/admin/?view=preview&id=<?= $page['id'] ?>" target="_blank" rel="noopener">Preview saved page ↗</a><a class="setting-link" href="/admin/?view=revisions&id=<?= $page['id'] ?>">Revision history (<?= $revisionCount ?>)</a></section>
<section class="panel"><h2>Page settings</h2><label>Page path<input name="route" value="<?= cmsEscape($page['route']) ?>" required <?= in_array($page['route'],['/','/asia/','/us/'],true) ? 'readonly' : '' ?>></label><p class="field-help">Changing a path redirects the previous URL.</p><label>Page group<input name="group_name" list="page-groups" maxlength="100" value="<?= cmsEscape($page['group_name']) ?>"></label><datalist id="page-groups"><?php foreach ($groups as $name): ?><option value="<?= cmsEscape($name) ?>"><?php endforeach ?></datalist></section>
<section class="panel"><h2>Search settings</h2><label>Search title<input name="seo_title" maxlength="490" placeholder="Use page title" value="<?= cmsEscape($page['seo_title'] ?? '') ?>"></label><label>Description<textarea name="meta_description" rows="4" maxlength="2000"><?= cmsEscape($description) ?></textarea></label><p class="field-help">A short description helps visitors understand this page in search results.</p></section></aside></div>
<div class="save-bar"><span id="save-state">All changes saved.</span><button>Save changes</button></div></form>
<div class="page-tools"><form method="post"><?= csrfInput() ?><input type="hidden" name="action" value="duplicate_page"><input type="hidden" name="id" value="<?= $page['id'] ?>"><button class="secondary">Duplicate page</button></form><?php if ($page['source_file']): ?><form method="post" data-confirm="Restore the original downloaded content? Your current version will be kept in revision history."><?= csrfInput() ?><input type="hidden" name="action" value="reset_page"><input type="hidden" name="id" value="<?= $page['id'] ?>"><input type="hidden" name="version" value="<?= $page['version'] ?>"><input type="hidden" name="title" value="<?= cmsEscape($page['title']) ?>"><input type="hidden" name="status" value="<?= cmsEscape($page['status']) ?>"><button class="secondary">Restore original content</button></form><?php endif ?></div>
<dialog id="media-picker"><div class="picker-heading"><h2>Choose an image</h2><button type="button" class="secondary" id="close-media-picker">Close</button></div><div class="picker-search"><input id="picker-query" placeholder="Search images" aria-label="Search images"><button type="button" id="search-media-picker">Search</button><a href="/admin/?view=media" target="_blank" rel="noopener">Upload image ↗</a></div><p id="picker-status" class="muted" role="status"></p><div id="picker-results"></div><button type="button" class="secondary" id="picker-more" hidden>Load more</button></dialog>
<?php endif; } catch (RuntimeException $e) { ?><div class="alert error"><?= cmsEscape($e->getMessage()) ?></div><?php } ?>
