<?php
declare(strict_types=1);
$search = trim((string)($_GET['q'] ?? ''));
$status = in_array($_GET['status'] ?? '', ['published','draft','trashed'], true) ? $_GET['status'] : 'all';
$region = in_array($_GET['region'] ?? '', ['global','asia','us'], true) ? $_GET['region'] : 'all';
$group = trim((string)($_GET['group'] ?? ''));
$sort = in_array($_GET['sort'] ?? '', ['title','path','updated'], true) ? $_GET['sort'] : 'updated';
$number = max(1, (int)($_GET['page'] ?? 1));
$counts = ['all'=>0,'published'=>0,'draft'=>0,'trashed'=>0];
foreach ($db->query('SELECT status, COUNT(*) AS total FROM indiba_cms_pages GROUP BY status') as $row) { $counts[$row['status']] = (int)$row['total']; if ($row['status'] !== 'trashed') $counts['all'] += (int)$row['total']; }
$groups = $db->query('SELECT DISTINCT group_name FROM indiba_cms_pages ORDER BY group_name')->fetchAll(PDO::FETCH_COLUMN);
$conditions = [$status === 'all' ? "status <> 'trashed'" : 'status = ?']; $parameters = $status === 'all' ? [] : [$status];
if ($search !== '') { $conditions[] = '(title LIKE ? OR route LIKE ?)'; $parameters[] = '%' . $search . '%'; $parameters[] = '%' . $search . '%'; }
if ($region === 'asia') $conditions[] = "route LIKE '/asia/%'";
if ($region === 'us') $conditions[] = "route LIKE '/us/%'";
if ($region === 'global') $conditions[] = "route NOT LIKE '/asia/%' AND route NOT LIKE '/us/%'";
if ($group !== '') { $conditions[] = 'group_name = ?'; $parameters[] = $group; }
$where = ' WHERE ' . implode(' AND ', $conditions);
$query = $db->prepare('SELECT COUNT(*) FROM indiba_cms_pages' . $where); $query->execute($parameters); $total = (int)$query->fetchColumn();
$number = min($number, max(1, (int)ceil($total / 30))); $offset = ($number - 1) * 30;
$order = ['title'=>'title, id', 'path'=>'route', 'updated'=>'updated_at DESC, id DESC'][$sort];
$query = $db->prepare('SELECT id, title, route, group_name, status, version, updated_at FROM indiba_cms_pages' . $where . " ORDER BY $order LIMIT 30 OFFSET $offset"); $query->execute($parameters); $pages = $query->fetchAll();
$pageLink = fn(array $changes = []) => '/admin/?' . http_build_query(array_replace(['view'=>'pages','q'=>$search,'status'=>$status,'region'=>$region,'group'=>$group,'sort'=>$sort], $changes));
?>
<div class="cms-page-intro"><p class="muted">Create, organize, and publish your English website pages.</p><a class="button" href="/admin/?view=new">+ Add page</a></div>
<nav class="status-tabs" aria-label="Filter by page status"><?php foreach (['all'=>'All pages','published'=>'Published','draft'=>'Drafts','trashed'=>'Trash'] as $key=>$label): ?><a href="<?= cmsEscape($pageLink(['status'=>$key,'page'=>1])) ?>" class="<?= $status===$key ? 'selected' : '' ?>"><?= $label ?> <span><?= number_format($counts[$key]) ?></span></a><?php endforeach ?></nav>
<form method="get" class="page-filters"><input type="hidden" name="view" value="pages"><input type="hidden" name="status" value="<?= $status ?>"><input name="q" placeholder="Search page titles or paths" value="<?= cmsEscape($search) ?>" aria-label="Search pages"><select name="region" aria-label="Region"><option value="all">All regions</option><?php foreach (['global'=>'Global','asia'=>'Asia','us'=>'United States'] as $key=>$label): ?><option value="<?= $key ?>" <?= $region===$key ? 'selected' : '' ?>><?= $label ?></option><?php endforeach ?></select><select name="group" aria-label="Page group"><option value="">All page groups</option><?php foreach ($groups as $name): ?><option value="<?= cmsEscape($name) ?>" <?= $group===$name ? 'selected' : '' ?>><?= cmsEscape($name) ?></option><?php endforeach ?></select><select name="sort" aria-label="Sort pages"><?php foreach (['updated'=>'Recently updated','title'=>'Title A–Z','path'=>'Page path'] as $key=>$label): ?><option value="<?= $key ?>" <?= $sort===$key ? 'selected' : '' ?>><?= $label ?></option><?php endforeach ?></select><button>Filter</button></form>
<form method="post" id="bulk-pages" class="bulk-toolbar"><?= csrfInput() ?><input type="hidden" name="action" value="bulk_pages"><select name="target_status" required aria-label="Bulk action"><option value="">Bulk actions</option><?php if ($status==='trashed'): ?><option value="draft">Restore as drafts</option><?php else: ?><option value="published">Publish</option><option value="draft">Move to drafts</option><option value="trashed">Move to Trash</option><?php endif ?></select><button class="secondary">Apply</button><span id="selected-count" class="muted">0 selected</span><span class="results-count"><?= number_format($total) ?> pages</span></form>
<section class="panel table-wrap cms-pages-table"><table><thead><tr><th class="checkbox-col"><input type="checkbox" id="select-all-pages" aria-label="Select all pages on this screen"></th><th>Page</th><th>Group / region</th><th>Status</th><th>Updated</th></tr></thead><tbody>
<?php foreach ($pages as $item): $itemRegion = str_starts_with($item['route'],'/asia/') ? 'Asia' : (str_starts_with($item['route'],'/us/') ? 'United States' : 'Global'); ?>
<tr><td class="checkbox-col"><input type="checkbox" name="ids[]" value="<?= $item['id'] ?>" form="bulk-pages" class="page-selection" aria-label="Select <?= cmsEscape($item['title']) ?>"><input type="hidden" name="versions[<?= $item['id'] ?>]" value="<?= $item['version'] ?>" form="bulk-pages"></td><td><a class="page-title" href="/admin/?view=edit&id=<?= $item['id'] ?>"><?= cmsEscape($item['title']) ?></a><small><?= cmsEscape($item['route']) ?></small><div class="row-actions"><?php if ($item['status']!=='trashed'): ?><a href="/admin/?view=edit&id=<?= $item['id'] ?>">Edit</a><a href="/admin/?view=preview&id=<?= $item['id'] ?>" target="_blank" rel="noopener">Preview</a><form method="post"><?= csrfInput() ?><input type="hidden" name="action" value="duplicate_page"><input type="hidden" name="id" value="<?= $item['id'] ?>"><button class="text-button">Duplicate</button></form><?php endif ?><form method="post" <?= $item['status']!=='trashed' ? 'data-confirm="Move this page to Trash? You can restore it later."' : '' ?>><?= csrfInput() ?><input type="hidden" name="action" value="page_status"><input type="hidden" name="id" value="<?= $item['id'] ?>"><input type="hidden" name="version" value="<?= $item['version'] ?>"><input type="hidden" name="target_status" value="<?= $item['status']==='trashed' ? 'draft' : 'trashed' ?>"><button class="text-button <?= $item['status']!=='trashed' ? 'danger-text' : '' ?>"><?= $item['status']==='trashed' ? 'Restore' : 'Trash' ?></button></form></div></td><td><span><?= cmsEscape($item['group_name']) ?></span><small><?= $itemRegion ?></small></td><td><span class="badge <?= $item['status'] ?>"><?= cmsEscape($item['status']) ?></span></td><td class="muted date-cell"><?= cmsEscape($item['updated_at']) ?></td></tr>
<?php endforeach ?></tbody></table><?php if (!$pages): ?><div class="empty"><h2><?= $status==='trashed' ? 'Trash is empty' : 'No pages found' ?></h2><p>Try changing the filters or create a new page.</p></div><?php endif ?></section>
<div class="pagination"><span>Page <?= $number ?> of <?= max(1, (int)ceil($total/30)) ?></span><div><?php if ($number>1): ?><a href="<?= cmsEscape($pageLink(['page'=>$number-1])) ?>">← Previous</a><?php endif ?><?php if ($offset+30<$total): ?><a href="<?= cmsEscape($pageLink(['page'=>$number+1])) ?>">Next →</a><?php endif ?></div></div>
