const { chromium } = require('../.tools/browser/node_modules/playwright');
const fs = require('node:fs');
const assert = require('node:assert/strict');

(async () => {
  const base = process.env.CMS_TEST_URL || 'http://127.0.0.1:9002';
  if (!['localhost', '127.0.0.1'].includes(new URL(base).hostname) || new URL(base).port === '9000') throw Error('Run against the isolated test portal, not the live site.');
  const credentials = fs.readFileSync('storage/cms-test-bootstrap.txt', 'utf8');
  const password = credentials.match(/^Password: (.+)$/m)[1];
  const browser = await chromium.launch({ executablePath: process.env.MIRROR_CHROME || 'C:/Users/sebastian/AppData/Local/ms-playwright/chromium-1228/chrome-win64/chrome.exe', headless: true });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
  const page = await context.newPage(); const errors = []; const checks = [];
  const pass = message => { checks.push(message); console.log('PASS ' + message); };
  page.on('pageerror', error => errors.push(error.message));
  await context.route('**/*', route => ['127.0.0.1', 'localhost'].includes(new URL(route.request().url()).hostname) ? route.continue() : route.abort());
  try {
    let response = await page.goto(base + '/admin/'); assert.equal(response.status(), 200);
    assert.equal(await page.locator('input[name=username]').count(), 1);
    const denied = await context.request.post(base + '/admin/', { form: { action: 'login', username: 'admin', password } });
    assert.equal(denied.status(), 403); pass('CSRF protection rejects forged requests');
    await page.locator('[name=username]').fill('admin'); await page.locator('[name=password]').fill('wrong-password');
    await page.getByRole('button', {name:'Sign in', exact:true}).click(); await page.waitForLoadState();
    assert.match(await page.locator('.error').innerText(), /incorrect/); pass('Incorrect credentials rejected');
    await page.locator('[name=username]').fill('admin'); await page.locator('[name=password]').fill(password);
    await page.getByRole('button', {name:'Sign in',exact:true}).click(); await page.waitForURL(base + '/admin/');
    assert.equal(await page.locator('.stats .stat').count(), 6); pass('Administrator login and overview');
    await page.screenshot({path:'storage/admin-desktop.png',fullPage:true});
    await page.goto(base + '/admin/?view=new');
    await page.locator('[name=title]').fill('CMS integration test'); await page.locator('[name=route]').fill('/cms-integration-test/');
    await page.getByRole('button', {name:'Create draft',exact:true}).click(); await page.waitForURL(/view=edit/);
    const editUrl = page.url();
    response = await context.request.get(base + '/cms-integration-test/'); assert.equal(response.status(), 404); pass('New drafts are hidden from public visitors');
    await page.goto(editUrl + '&mode=content');
    await page.locator('.text-block textarea').filter({hasText:'Add your English page content here.'}).fill('English content published from the management portal.');
    await page.locator('[name=status]').selectOption('published');
    await page.getByRole('button', {name:'Save changes',exact:true}).first().click(); await page.waitForLoadState();
    assert.equal(await page.locator('.error').count(),0);
    response = await context.request.get(base + '/cms-integration-test/'); assert.equal(response.status(),200);
    assert.match(await response.text(),/English content published from the management portal/); pass('Page text edits publish through MySQL');
    const head = await context.request.head(base + '/cms-integration-test/'); assert.equal(head.status(),200); assert.equal((await head.body()).length,0); pass('Managed pages support HEAD requests');
    const version = await page.locator('[name=version]').inputValue();
    const csrf = await page.locator('[name=csrf]').first().inputValue(); const id = new URL(editUrl).searchParams.get('id');
    const conflict = await context.request.post(base + '/admin/?view=edit&id=' + id, {form:{csrf, action:'save_page', id, version: String(Number(version)-1), mode:'html', title:'Stale update', status:'published', html:'<!doctype html><html lang="en"><head><title>Stale</title></head><body>Stale content</body></html>'}});
    assert.match(await conflict.text(), /Someone else changed this page/); pass('Concurrent edits cannot overwrite a newer version');
    await page.goto(editUrl + '&mode=html');
    const html = await page.locator('[name=html]').inputValue(); await page.locator('[name=html]').fill(html.replace('</main>', '<p>Additional HTML block.</p></main>'));
    await page.getByRole('button', {name:'Save changes',exact:true}).first().click(); await page.waitForLoadState();
    response = await context.request.get(base + '/cms-integration-test/'); assert.match(await response.text(), /Additional HTML block/); pass('HTML source editing');
    await page.goto(base + '/admin/?view=media');
    await page.getByRole('button',{name:'+ Add new media file',exact:true}).click();
    await page.locator('[name=file]').setInputFiles({name:'cms-test.png', mimeType:'image/png', buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jbuQAAAAASUVORK5CYII=', 'base64')});
    await page.getByRole('button',{name:'Upload file',exact:true}).click(); await page.waitForURL(/filter=uploads/);
    const uploaded = await page.locator('.media-card input[aria-label="File URL"]').first().inputValue(); assert.match(uploaded,/^\/uploads\/[a-f0-9]{32}\.png$/);
    fs.writeFileSync('storage/cms-test-upload.json',JSON.stringify({path:uploaded}));
    response = await context.request.get(base+uploaded); assert.equal(response.status(),200); pass('Image uploads and media library');
    await page.getByRole('button',{name:'+ Add new media file',exact:true}).click();
    await page.locator('[name=file]').setInputFiles({name:'exploit.php',mimeType:'application/x-php',buffer:Buffer.from('<?php echo "unsafe";')});
    await page.getByRole('button',{name:'Upload file',exact:true}).click(); await page.waitForLoadState();
    assert.match(await page.locator('.error').innerText(),/JPG, PNG/); pass('Executable uploads rejected');
    await page.goto(base + '/admin/?view=pages&q=ct8');
    const productEdit = (await page.locator('a.page-title').first().getAttribute('href')) + '&mode=visual'; await page.goto(base+productEdit);
    await page.locator('.image-edit input[name$="[src]"]').first().fill(uploaded);
    await page.getByRole('button',{name:'Save changes',exact:true}).first().click(); await page.waitForLoadState();
    assert.equal(await page.locator('.error').count(),0);
    response=await context.request.get(base+'/asia/products/ct8/'); assert.match(await response.text(),new RegExp(uploaded));
    await page.goto(base+'/asia/products/ct8/',{waitUntil:'domcontentloaded',timeout:120000}); await page.waitForTimeout(4000);
    assert.equal(errors.length,0); pass('Existing mirrored page saves with its scripts intact');
    await page.goto(base+productEdit); page.once('dialog',dialog=>dialog.accept());
    await page.getByRole('button',{name:'Restore original content',exact:true}).click(); await page.waitForLoadState();
    response=await context.request.get(base+'/asia/products/ct8/'); assert.ok(!(await response.text()).includes(uploaded)); pass('Original snapshot restoration');
    await page.goto(base + '/admin/'); await page.setViewportSize({width:390,height:844});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
    await page.screenshot({path:'storage/admin-mobile.png',fullPage:true});
    await page.goto(base+'/admin/?view=pages'); assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true); pass('Mobile overview and page list');
    await page.setViewportSize({width:1440,height:1000});
    await page.goto(editUrl + '&mode=visual');
    const paragraphField = await page.locator('.rich-editor').filter({hasText:'English content published from the management portal.'}).getAttribute('data-field');
    const paragraph = page.locator('[data-field="' + paragraphField + '"]');
    await paragraph.fill('Visual CMS text with formatting.');
    await paragraph.evaluate(element=>{const range=document.createRange();range.selectNodeContents(element);const selection=getSelection();selection.removeAllRanges();selection.addRange(range);});
    await page.getByRole('button',{name:'Bold',exact:true}).click();
    await page.locator('[name=group_name]').fill('Company');
    await page.locator('[name=seo_title]').fill('Search title $1 & company');
    await page.locator('[name=meta_description]').fill('An English description for search results.');
    await page.locator('[name=route]').fill('/cms-renamed-page/');
    await page.getByRole('button',{name:'Save changes',exact:true}).first().click(); await page.waitForLoadState();
    response=await context.request.get(base+'/cms-renamed-page/'); const saved=await response.text();
    assert.match(saved,/<strong>Visual CMS text with formatting\.<\/strong>/); assert.match(saved,/<title>Search title \$1 &amp; company<\/title>/); assert.match(saved,/An English description for search results/);
    const redirected=await context.request.get(base+'/cms-integration-test/',{maxRedirects:0}); assert.equal(redirected.status(),301); assert.equal(redirected.headers().location,'/cms-renamed-page/'); pass('Visual formatting, search settings, and automatic URL redirects');
    await page.getByRole('button',{name:'+ Paragraph',exact:true}).click(); await page.locator('[name="new_blocks[0][text]"]').fill('A new paragraph added visually.');
    await page.locator('[name=status]').selectOption('draft'); await page.getByRole('button',{name:'Save changes',exact:true}).first().click(); await page.waitForLoadState();
    response=await context.request.get(base+'/cms-renamed-page/'); assert.equal(response.status(),404);
    response=await context.request.get(base+'/admin/?view=preview&id='+id); assert.equal(response.status(),200); assert.match(await response.text(),/A new paragraph added visually/); assert.equal(response.headers()['x-robots-tag'],'noindex, nofollow');
    const anonymous=await browser.newContext(); const deniedPreview=await anonymous.request.get(base+'/admin/?view=preview&id='+id); assert.ok(!(await deniedPreview.text()).includes('A new paragraph added visually')); await anonymous.close(); pass('Private draft preview and adding content blocks');
    await page.goto(base+'/admin/?view=pages&status=draft&group=Company'); assert.equal(await page.locator('a.page-title').count(),1); pass('Status and page group filters');
    await page.getByRole('button',{name:'Duplicate',exact:true}).first().click(); await page.waitForURL(/view=edit/);
    const duplicateId=new URL(page.url()).searchParams.get('id'); assert.notEqual(duplicateId,id); assert.equal(await page.locator('[name=status]').inputValue(),'draft'); pass('Duplicate page starts as a draft');
    await page.goto(base+'/admin/?view=pages&status=draft&group=Company');
    await page.locator('#select-all-pages').check(); assert.match(await page.locator('#selected-count').innerText(),/2 selected/);
    await page.locator('#bulk-pages [name=target_status]').selectOption('published'); await page.locator('#bulk-pages button').click(); await page.waitForLoadState(); assert.match(await page.locator('.success').innerText(),/2 pages updated/); pass('Bulk publishing');
    await page.goto(base+'/admin/?view=pages&group=Company'); await page.locator('#select-all-pages').check(); await page.locator('#bulk-pages [name=target_status]').selectOption('trashed'); page.once('dialog',dialog=>dialog.accept()); await page.locator('#bulk-pages button').click(); await page.waitForLoadState();
    response=await context.request.get(base+'/cms-renamed-page/'); assert.equal(response.status(),404); assert.equal(await page.locator('a.page-title').count(),2); pass('Trash hides pages without deleting content');
    await page.locator('#select-all-pages').check(); await page.locator('#bulk-pages [name=target_status]').selectOption('draft'); await page.locator('#bulk-pages button').click(); await page.waitForLoadState(); assert.match(await page.locator('.success').innerText(),/2 pages updated/); pass('Bulk restore returns pages to drafts');
    await page.goto(base+'/admin/?view=revisions&id='+id); assert.ok(await page.locator('.revision-row').count()>0);
    page.once('dialog',dialog=>dialog.accept()); await page.getByRole('button',{name:'Restore version',exact:true}).first().click(); await page.waitForURL(/view=edit/); assert.equal(await page.locator('[name=status]').inputValue(),'draft'); pass('Revision history and safe draft restoration');
    await page.goto(base+productEdit); await page.getByRole('button',{name:'Choose image',exact:true}).first().click(); await page.waitForSelector('.picker-image'); await page.locator('.picker-image').first().click(); assert.equal(await page.locator('#media-picker').evaluate(dialog=>dialog.open),false); pass('Media picker selects images without leaving the editor');
    page.once('dialog',dialog=>dialog.accept()); await page.goto(base+'/admin/?view=pages');
    await page.goto(base+'/admin/?view=account');
    const newPassword='Changed-test-password-' + Date.now();
    await page.locator('[name=current_password]').fill(password); await page.locator('[name=new_password]').fill(newPassword); await page.locator('[name=confirm_password]').fill(newPassword);
    await page.getByRole('button',{name:'Change password',exact:true}).click(); await page.waitForLoadState();
    assert.match(await page.locator('.success').innerText(),/password has been changed/); pass('Password changes');
    await page.getByRole('button',{name:'Sign out',exact:true}).click(); await page.waitForLoadState(); assert.equal(await page.locator('[name=username]').count(),1); pass('Session logout');
    await page.locator('[name=username]').fill('admin'); await page.locator('[name=password]').fill(newPassword); await page.getByRole('button',{name:'Sign in',exact:true}).click(); await page.waitForLoadState();
    assert.equal(await page.locator('.stats').count(),1); pass('Updated password authenticates');
    fs.writeFileSync('storage/cms-check.json',JSON.stringify({checks,errors},null,2));
    console.log(`${checks.length} portal checks passed.`);
  } finally { await browser.close(); }
})().catch(error => {console.error(error);process.exit(1);});
