const {chromium} = require('../.tools/browser/node_modules/playwright');
const fs = require('node:fs');
const assert = require('node:assert/strict');
(async()=>{
 const base='http://127.0.0.1:9002';const password=fs.readFileSync('storage/cms-test-bootstrap.txt','utf8').match(/^Password: (.+)$/m)[1];
 const browser=await chromium.launch({executablePath:process.env.MIRROR_CHROME||'C:/Users/sebastian/AppData/Local/ms-playwright/chromium-1228/chrome-win64/chrome.exe',headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];const checks=[];const pass=name=>{checks.push(name);console.log('PASS '+name);};
 page.on('pageerror',error=>errors.push(error.message));
 await page.route('**/*',route=>['127.0.0.1','localhost'].includes(new URL(route.request().url()).hostname)?route.continue():route.abort());
 const waitEditor=()=>page.waitForFunction(()=>window.tinymce?.get('classic-content')?.initialized);
 const save=async()=>{await Promise.all([page.waitForNavigation({waitUntil:'domcontentloaded',timeout:120000}),page.getByRole('button',{name:'Save changes',exact:true}).first().click()]);await waitEditor();assert.equal(await page.locator('.error').count(),0);};
 try{
  await page.goto(base+'/admin/');await page.locator('[name=username]').fill('admin');await page.locator('[name=password]').fill(password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForLoadState();
  await page.goto(base+'/admin/?view=new');await page.locator('[name=title]').fill('Classic editor test');await page.locator('[name=route]').fill('/classic-editor-test/');await page.getByRole('button',{name:'Create draft',exact:true}).click();await page.waitForLoadState();await waitEditor();
  assert.equal(await page.locator('[name=mode]').inputValue(),'classic');pass('Classic TinyMCE editor is the default');
  await page.evaluate(()=>{const editor=tinymce.get('classic-content');editor.setContent('<h1>Classic editor test</h1><p>Editable paragraph with <strong>bold</strong> text.</p><ul><li>First item</li><li>Second item</li></ul><table class="cms-content-table"><tbody><tr><th>Name</th><th>Value</th></tr><tr><td>English content</td><td>42</td></tr></tbody></table><p style="text-align:center;color:#087b87;font-size:20px">Centered color text</p>');editor.setDirty(true);editor.dispatch('change');});
  await page.locator('[name=status]').selectOption('published');await save();
  let response=await page.request.get(base+'/classic-editor-test/');let html=await response.text();assert.match(html,/<table/);assert.match(html,/<ul>/);assert.match(html,/text-align: center|text-align:center/);assert.match(html,/English content/);pass('Rich text, lists, tables, colors, and alignment persist');
  const code=page.locator('#classic-code');const visualButton=page.getByRole('button',{name:'Visual',exact:true});const codeButton=page.getByRole('button',{name:'Code',exact:true});
  await codeButton.click();assert.equal(await code.isVisible(),true);assert.equal(await page.locator('.tox-tinymce').isVisible(),false);assert.match(await code.inputValue(),/English content/);assert.equal(await codeButton.getAttribute('aria-pressed'),'true');
  await visualButton.click();assert.equal(await code.isVisible(),false);assert.equal(await page.locator('#classic-changed').inputValue(),'0');pass('Visual and Code views switch without marking unchanged content as edited');
  await page.evaluate(()=>{const editor=tinymce.get('classic-content');editor.insertContent('<p>Unsaved visual marker</p>');});await codeButton.click();assert.match(await code.inputValue(),/Unsaved visual marker/);
  await code.fill((await code.inputValue())+'\n<h2>HTML code heading</h2><p><em>Code formatting marker</em></p>');assert.equal(await page.locator('#classic-changed').inputValue(),'1');
  await visualButton.click();assert.equal(await page.evaluate(()=>tinymce.get('classic-content').getBody().querySelector('em')?.textContent),'Code formatting marker');await save();
  response=await page.request.get(base+'/classic-editor-test/');html=await response.text();assert.match(html,/Unsaved visual marker/);assert.match(html,/<h2>HTML code heading<\/h2>/);assert.match(html,/<em>Code formatting marker<\/em>/);pass('Unsaved edits survive Visual to Code to Visual and save');
  await codeButton.click();await code.fill((await code.inputValue())+'\n<p class="code-save-marker">Saved directly from Code</p>');
  await page.screenshot({path:'storage/classic-code-desktop.png',fullPage:false});await save();response=await page.request.get(base+'/classic-editor-test/');assert.match(await response.text(),/class="code-save-marker">Saved directly from Code/);pass('HTML edits save directly from Code mode');
  await codeButton.click();const beforeMedia=await code.inputValue();await code.evaluate(element=>element.setSelectionRange(element.value.length,element.value.length));
  await page.getByRole('button',{name:'Add media',exact:true}).click();await page.waitForSelector('.picker-image');await page.locator('.picker-image').first().click();assert.equal(await code.isVisible(),true);assert.ok((await code.inputValue()).startsWith(beforeMedia));assert.match((await code.inputValue()).slice(beforeMedia.length),/<img/);await save();pass('Add media inserts HTML in Code mode without losing edits');
  await page.evaluate(()=>{const editor=tinymce.get('classic-content');editor.undoManager.transact(()=>editor.insertContent('<p>Undo test marker</p>'));editor.undoManager.undo();});
  assert.equal(await page.evaluate(()=>tinymce.get('classic-content').getContent().includes('Undo test marker')),false);
  await page.evaluate(()=>tinymce.get('classic-content').undoManager.redo());assert.equal(await page.evaluate(()=>tinymce.get('classic-content').getContent().includes('Undo test marker')),true);pass('Editor undo and redo');
  await page.getByRole('button',{name:'Columns',exact:true}).click();await page.getByRole('menuitem',{name:'2 columns',exact:true}).click();
  await page.getByRole('button',{name:'Callout',exact:true}).click();
  await page.getByRole('button',{name:'Button',exact:true}).click();const dialog=page.locator('.tox-dialog');await dialog.locator('input').nth(0).fill('Contact us');await dialog.locator('input').nth(1).fill('/asia/contact/');await dialog.getByRole('button',{name:'Insert',exact:true}).click();await save();
  response=await page.request.get(base+'/classic-editor-test/');html=await response.text();assert.match(html,/cms-content-columns/);assert.match(html,/cms-content-callout/);assert.match(html,/cms-content-button/);assert.match(html,/Contact us/);pass('Columns, callouts, and styled buttons');
  await page.getByRole('button',{name:'Add media',exact:true}).click();await page.waitForSelector('.picker-image');await page.locator('.picker-image').first().click();await save();
  response=await page.request.get(base+'/classic-editor-test/');assert.match(await response.text(),/<img/);pass('Classic editor inserts images from the media library');
  const csrf=await page.locator('#page-editor [name=csrf]').inputValue();
  const uploaded=await page.request.post(base+'/admin/',{multipart:{action:'editor_upload',csrf,file:{name:'classic-upload.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jbuQAAAAASUVORK5CYII=','base64')}}});assert.equal(uploaded.status(),200);const asset=await uploaded.json();assert.match(asset.location,/^\/uploads\/[a-f0-9]{32}\.png$/);
  const rejected=await page.request.post(base+'/admin/',{multipart:{action:'editor_upload',csrf,file:{name:'bad.php',mimeType:'application/x-php',buffer:Buffer.from('<?php echo 1;')}}});assert.equal(rejected.status(),422);assert.ok((await rejected.json()).error);pass('Editor upload API validates images and rejects executable files');
  await page.evaluate(()=>{const editor=tinymce.get('classic-content');const encoded='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jbuQAAAAASUVORK5CYII=';const blob=new Blob([Uint8Array.from(atob(encoded),character=>character.charCodeAt(0))],{type:'image/png'});const info=editor.editorUpload.blobCache.create('upload-test',blob,encoded);editor.editorUpload.blobCache.add(info);editor.insertContent('<p><img src="'+info.blobUri()+'" alt="Inline upload"></p>');});await save();
  response=await page.request.get(base+'/classic-editor-test/');html=await response.text();assert.match(html,/Inline upload/);assert.match(html,/\/uploads\//);assert.ok(!html.includes('blob:'));pass('Pasted image uploads complete before page save');
  await page.screenshot({path:'storage/classic-editor-desktop.png',fullPage:false});
  await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:'storage/classic-editor-mobile.png',fullPage:false});await codeButton.click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:'storage/classic-code-mobile.png',fullPage:false});await visualButton.click();pass('Classic Visual and Code views adapt to mobile');
  await page.setViewportSize({width:1440,height:1000});await page.goto(base+'/admin/?view=pages&q=ct8');await page.locator('a.page-title').first().click();await waitEditor();
  await page.evaluate(()=>{const editor=tinymce.get('classic-content');editor.insertContent('<p>CT8 classic edit</p>');editor.setDirty(true);editor.dispatch('change');});await save();
  response=await page.request.get(base+'/asia/products/ct8/');html=await response.text();assert.match(html,/CT8 classic edit/);assert.ok(!html.includes('data-cms-lock'));assert.match(html,/cms-content.css/);
  await page.goto(base+'/asia/products/ct8/',{waitUntil:'domcontentloaded',timeout:120000});await page.waitForTimeout(4000);assert.equal(errors.length,0);pass('Original product layout and scripts survive classic editing');
  fs.writeFileSync('storage/classic-check.json',JSON.stringify({checks,errors},null,2));console.log(`${checks.length} classic editor checks passed.`);
 }finally{await browser.close();}
})().catch(error=>{console.error(error);process.exit(1);});
